# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ChangeDetection
                                 A QGIS plugin
 Retrives CCDC's information and plot chart for a given point.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-04
        copyright            : (C) 2023 by Daniel Moraes
        email                : moraesd90@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ChangeDetection class from file ChangeDetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #

    from .CCDC_retriever import ChangeDetection
    return ChangeDetection(iface)
